/**
 * Review & Verdict Extraction — pure functions for parsing subagent output.
 *
 * Extracted from extensions/index.ts for maintainability.
 * These functions have no dependency on pi-coder module-level state.
 */

import type { ReviewVerdict } from "./types.ts";

// ---------------------------------------------------------------------------
// Intercom receipt detection
// ---------------------------------------------------------------------------

/**
 * Detect whether a raw content array is a pi-intercom delivery receipt.
 * These receipts are generated by pi-subagents when the orchestrator
 * receives results via intercom rather than direct tool_result.
 */
export function isIntercomReceipt(rawContent: unknown): boolean {
  if (!Array.isArray(rawContent)) return false;
  const textBlock = rawContent.find(
    (c: unknown) => typeof c === "object" && c !== null && (c as Record<string, unknown>).type === "text"
  );
  if (!textBlock) return false;
  const text = (textBlock as { type: string; text?: string }).text ?? "";
  return /Delivered\s+.*\s+via intercom/i.test(text);
}

// ---------------------------------------------------------------------------
// Details diagnostics extraction
// ---------------------------------------------------------------------------

/**
 * Extract diagnostic text info from details object for logging.
 * Returns actual content length and preview — not the always-0 values
 * we were logging before (which checked typeof details === "string").
 */
export function extractDetailsDiagnostics(details: unknown): {
  hasFinalOutput: boolean;
  textLength: number;
  firstHundredChars: string;
} {
  if (!details || typeof details !== "object") {
    return { hasFinalOutput: false, textLength: 0, firstHundredChars: "" };
  }
  const r = details as Record<string, unknown>;
  let text = "";
  let hasFinalOutput = false;

  if (Array.isArray(r.results)) {
    const firstResult = (r.results as Array<Record<string, unknown>>)[0];
    if (firstResult) {
      hasFinalOutput = typeof firstResult.finalOutput === "string";
      if (hasFinalOutput) {
        text = firstResult.finalOutput as string;
      }
    }
  } else if (typeof r.content === "string") {
    text = r.content;
    hasFinalOutput = false; // Not finalOutput, but there IS text
  } else if (Array.isArray(r.content)) {
    text = (r.content as Array<{ type: string; text?: string }>)
      .filter((c: { type: string }) => c.type === "text")
      .map((c: { text?: string }) => c.text ?? "")
      .join("\n");
  }

  return {
    hasFinalOutput,
    textLength: text.length,
    firstHundredChars: text.slice(0, 100).replace(/\n/g, "\\n"),
  };
}

// ---------------------------------------------------------------------------
// Subagent target agent extraction
// ---------------------------------------------------------------------------

/**
 * Extract the target agent name from a subagent tool call input.
 * Checks common parameter names used by pi-subagents.
 */
function extractSubagentTarget(input: Record<string, unknown>): string | undefined {
  return (input.agent as string) ?? (input.name as string) ?? undefined;
}

// ---------------------------------------------------------------------------
// Subagent usage extraction
// ---------------------------------------------------------------------------

/**
 * Extract subagent usage data from a pi-subagents Details tool result.
 *
 * pi-subagents provides usage inside `details.results[0].usage` with shape:
 *   { input, output, cacheRead, cacheWrite, cost, turns }
 * and model/exitCode/error on `details.results[0]` itself.
 *
 * This replaces the old `extractTokenUsage()` which incorrectly read
 * `details.usage.prompt_tokens` (OpenAI shape) — a path that never exists
 * on the pi-subagents Details object.
 */
export interface SubagentUsage {
  input: number;
  output: number;
  cacheRead: number;
  cacheWrite: number;
  cost: number;
  turns: number;
  model: string | null;
  exitCode: number;
  error: string | null;
}

function extractSubagentUsage(details: unknown): SubagentUsage | null {
  if (!details || typeof details !== "object") return null;
  const d = details as { results?: Array<Record<string, unknown>> };
  const firstResult = d.results?.[0];
  if (!firstResult) return null;

  const usage = firstResult.usage as {
    input?: number;
    output?: number;
    cacheRead?: number;
    cacheWrite?: number;
    cost?: number;
    turns?: number;
  } | undefined;

  if (!usage) return null;
  if ((usage.input ?? 0) === 0 && (usage.output ?? 0) === 0 && (usage.cost ?? 0) === 0) return null;

  return {
    input: usage.input ?? 0,
    output: usage.output ?? 0,
    cacheRead: usage.cacheRead ?? 0,
    cacheWrite: usage.cacheWrite ?? 0,
    cost: usage.cost ?? 0,
    turns: usage.turns ?? 0,
    model: typeof firstResult.model === "string" ? firstResult.model : null,
    exitCode: typeof firstResult.exitCode === "number" ? firstResult.exitCode : 0,
    error: typeof firstResult.error === "string" ? firstResult.error : null,
  };
}

export { extractSubagentUsage, extractSubagentTarget };

// ---------------------------------------------------------------------------
// Review verdict extraction
// ---------------------------------------------------------------------------

/**
 * Extract review verdict from a subagent output (reviewer agent).
 * Looks for common verdict patterns in the text output.
 *
 * Tier 0 (highest priority): Structured ---VERDICT--- block.
 * Tier 1 (fallback): Emoji verdict markers — uses LAST occurrence
 * in the text to avoid false positives from emojis in prose.
 * Tier 2 (fallback): Text-based pattern matching on full text.
 *
 * @param result - The subagent result (Details object with results array,
 *   or a content string/array).
 * @param rawContentText - Optional fallback text source. When pi-intercom
 *   receipt path strips `finalOutput` from the Details object, the
 *   verdict may still be present in the raw content. This parameter
 *   is tried when `finalOutput` is unavailable.
 */
export function extractReviewVerdict(result: unknown, rawContentText?: string): ReviewVerdict | null {
  if (!result || typeof result !== "object") return null;

  const r = result as Record<string, unknown>;

  // Extract text from the pi-subagents Details format:
  // details = { mode, results: [{ finalOutput, messages, ... }], ... }
  // Fallback: raw content blocks (for tests or non-standard formats)
  // Fallback: rawContentText parameter (when intercom receipt strips finalOutput)
  let text = "";
  if (Array.isArray(r.results)) {
    // pi-subagents Details format — use finalOutput from first result
    const firstResult = (r.results as Array<Record<string, unknown>>)[0];
    if (firstResult) {
      if (typeof firstResult.finalOutput === "string") {
        text = firstResult.finalOutput;
      }
    }
  } else if (typeof r.content === "string") {
    text = r.content;
  } else if (Array.isArray(r.content)) {
    // Tool result content is often an array of content blocks
    text = (r.content as Array<{ type: string; text?: string }>)
      .filter((c: { type: string }) => c.type === "text")
      .map((c: { text?: string }) => c.text ?? "")
      .join("\n");
  }

  // Fallback: try rawContentText when primary source yielded nothing
  // (e.g., pi-intercom receipt stripped finalOutput to undefined)
  if (!text && typeof rawContentText === "string" && rawContentText.length > 0) {
    text = rawContentText;
  }

  if (!text) return null;

  // --- Tier 0: Structured verdict block (highest priority) ---
  // Parse ---VERDICT--- blocks from the reviewer's output.
  // This is the primary mechanism; emoji/text patterns are fallback for
  // reviews that haven't adopted the block format yet.
  const verdictBlockMatch = text.match(/---VERDICT---\s*\n\s*VERDICT:\s*(approved|needs_changes)\s*\n(?:\s*FIX_TYPE:\s*(functional|non-functional|non_functional)\s*\n)?\s*---END VERDICT---[\s\S]*/i);

  if (verdictBlockMatch) {
    const blockVerdict = verdictBlockMatch[1].toLowerCase() as "approved" | "needs_changes";

    if (blockVerdict === "approved") {
      return { verdict: "approved" };
    }

    // needs_changes: extract fix type from block
    let fixType: "functional" | "non-functional" = "functional"; // Safe default
    if (verdictBlockMatch[2]) {
      const rawFixType = verdictBlockMatch[2].toLowerCase();
      fixType = rawFixType === "non_functional" || rawFixType === "non-functional" ? "non-functional" : "functional";
    }

    return {
      verdict: "needs_changes",
      fixType,
      issues: [], // Block format doesn't carry structured issues
    };
  }

  // --- Tier 1: Emoji-based verdict extraction (fallback) ---
  // Use LAST occurrence to avoid false positives from emojis in prose.
  // The reviewer's verdict appears at the END of the review.

  const approvedIndex = text.lastIndexOf("✅");
  const rejectIndex = text.lastIndexOf("❌");
  const changesIndex = text.lastIndexOf("⚠️");

  let emojiVerdict: "approved" | "needs_changes" | null = null;

  if (approvedIndex !== -1 || rejectIndex !== -1 || changesIndex !== -1) {
    // Build a list of (verdict, index) pairs for emojis that were found
    const verdicts: Array<{ verdict: "approved" | "needs_changes"; index: number }> = [];

    if (approvedIndex !== -1) {
      verdicts.push({ verdict: "approved", index: approvedIndex });
    }
    if (rejectIndex !== -1) {
      verdicts.push({ verdict: "needs_changes", index: rejectIndex });
    }
    if (changesIndex !== -1) {
      verdicts.push({ verdict: "needs_changes", index: changesIndex });
    }

    // Sort by index descending — the LAST emoji in text wins
    verdicts.sort((a, b) => b.index - a.index);
    emojiVerdict = verdicts[0].verdict;
  }

  // --- Tier 2: Text-based pattern matching (fallback) ---
  // Search the full text (no 500-char limit) for text-only verdicts.
  // Only used if Tier 1 didn't find any emoji markers.
  let textVerdict: "approved" | "needs_changes" | null = null;
  if (emojiVerdict === null) {
    if (/\*\*Verdict:\*\*\s*approved/i.test(text)) {
      textVerdict = "approved";
    } else if (/\*\*Verdict:\*\*\s*(?:request\s+changes|needs\s+changes)/i.test(text)) {
      textVerdict = "needs_changes";
    } else if (/approved/i.test(text)) {
      textVerdict = "approved";
    } else if (/needs.?changes|request.?changes/i.test(text)) {
      textVerdict = "needs_changes";
    }
  }

  const verdict = emojiVerdict ?? textVerdict;
  if (verdict === null) return null;

  // For approved verdicts, no additional data needed
  if (verdict === "approved") {
    return { verdict: "approved" };
  }

  // --- needs_changes: extract fix type and issue counts ---

  // Extract fix type classification from reviewer output
  let fixType: "functional" | "non-functional" = "functional"; // Safe default
  const fixTypeMatch = text.match(/fix.?type:\s*(functional|non-functional|non_functional)/i);
  if (fixTypeMatch) {
    fixType = fixTypeMatch[1].toLowerCase().replace("_", "-") === "non-functional" ? "non-functional" : "functional";
  }

  return {
    verdict: "needs_changes",
    fixType,
    issues: [], // Regex extraction cannot produce structured issues
  };
}
